title: <TheRealADizzle's First website>
description: <This is my first website created by your one and only ADizzle :)>
theme: jekyll-theme-time-machine
TikTok_Username: <a_dizzlefosizzle>
GitHub_Username: <TheRealADizzle>
